### ISSUE TITLE
Readme 오타

### ISSUE THREAD

**Issue by kdh8219** [CodingVillainKor/manim-kor#1]
항상 영상 잘 보고 있습니다!
https://github.com/CodingVillainKor/manim-kor/blob/54a1c1e55fce365330e2208faa7511055e3b72ab/README.md?plain=1#L32
attention folder로 수정이 필요할 것 같습니다!

**Comment by CodingVillainKor** [comment]
안녕하세요!

반영했습니다. 감사합니다!
